# Generated by Django 4.2.7 on 2023-11-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_time',
            field=models.DateField(null=True),
        ),
    ]
