# Generated by Django 4.2.7 on 2023-11-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0003_alter_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userData',
        ),
    ]
