# Generated by Django 4.2.7 on 2023-11-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0004_rename_user_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
