# Generated by Django 4.2.7 on 2023-11-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBoardBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarddata',
            name='team_id',
            field=models.IntegerField(null=True),
        ),
    ]
