# Generated by Django 4.2.7 on 2023-11-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBoardBase', '0002_boarddata_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=128)),
                ('user_id', models.IntegerField(null=True)),
                ('creation_time', models.DateField(null=True)),
                ('status', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='boarddata',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boarddata',
            name='status',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
