# Generated by Django 4.2.7 on 2023-11-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBoardBase', '0003_taskdata_alter_boarddata_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarddata',
            name='status',
            field=models.CharField(blank=True, default='OPEN', max_length=15),
        ),
    ]
