# Generated by Django 4.2.7 on 2023-11-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=128)),
                ('admin', models.CharField(max_length=64)),
                ('creation_time', models.DateField(null=True)),
                ('users', models.TextField()),
            ],
        ),
    ]
