# Generated by Django 4.2.7 on 2023-11-04 00:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamBase', '0027_alter_teamdata_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='users',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=55, size=5),
        ),
    ]
