# Generated by Django 4.2.7 on 2023-11-04 10:08

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamBase', '0034_alter_teamdata_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='users',
            field=django_mysql.models.ListTextField(models.IntegerField(), max_length=50, size=50),
        ),
    ]
